topics: 
  - id: MORTGAGE 
    name: "Ипотека / госпрограммы" 
    synonyms: ["семейная ипотека","льготная ипотека","ставка 6%","господдержка","субсидия"] 
  - id: FORCED_BUNDLE 
    name: "Навязанные услуги / пакеты" 
    synonyms: ["навязанная услуга","подписка","ДК+","пакет услуг","обязательный пакет"] 
    - id: INSURANCE 
      name: "Страхование" 
      synonyms: ["страховой полис","страховка","страховая премия"] 
    - id: MOBILE_APP 
      name: "Мобильное приложение" 
      synonyms: ["приложение","мобильный банк","зависает","краш","обновление","окко"] 
    - id: ONLINE_BANK 
      name: "Онлайн-банк / сайт" 
      synonyms: ["интернет-банк","личный кабинет","сайт","веб-версия"] 
    - id: BRANCH_SERVICE 
      name: "Обслуживание в отделении" 
      synonyms: ["отделение","операционист","очередь","сотрудник","офис"] 
    - id: SUPPORT 
      name: "Поддержка / колл-центр / чат" 
      synonyms: ["поддержка","оператор","чат","горячая линия"] 
    - id: FEES 
      name: "Комиссии и платежи" 
      synonyms: ["комиссия","списание","тариф","плата"] 
    - id: CARDS 
      name: "Карты / кэшбэк" 
      synonyms: ["карта","кэшбэк","кешбэк","дебетовая","кредитная"] 
    - id: LOANS 
      name: "Кредиты (не ипотека)" 
      synonyms: ["кредит","потреб","рефинансирование"]
    - id: RATES 
      name: "Ставки и проценты" 
      synonyms: ["процентная ставка","проценты","переплата"] 
    - id: SECURITY 
      name: "Мошенничество / безопасность" 
      synonyms: ["мошенник","безопасность","потеря средств","подозрительные операции"] 

sentiment_labels: ["neg","neu","pos"]