topics:
  - id: DEBIT_CARDS
    name: "Дебетовые карты"
    synonyms: ["дебетовая карта","дебет","карта для оплаты","снятие наличных с карты"]

  - id: CREDIT_CARDS
    name: "Кредитные карты"
    synonyms: ["кредитная карта","кредитка","лимит","рассрочка"]

  - id: CASH_LOANS
    name: "Кредиты наличными"
    synonyms: ["кредит наличными","потребительский кредит","наличка","кредит без залога"]

  - id: DEPOSITS
    name: "Вклады"
    synonyms: ["вклад","депозит","сберегательный счёт","накопительный счёт"]

  - id: MORTGAGE
    name: "Ипотека"
    synonyms: ["ипотека","ипотечный кредит","жилищный кредит","квартира в ипотеку"]

  - id: AUTO_LOANS
    name: "Автокредиты"
    synonyms: ["автокредит","кредит на машину","кредит на авто"]

  - id: REFINANCE_LOANS
    name: "Рефинансирование кредитов"
    synonyms: ["рефинансирование кредита","перекредитование","снижение ставки по кредиту"]

  - id: REFINANCE_MORTGAGE
    name: "Рефинансирование ипотеки"
    synonyms: ["рефинансирование ипотеки","перекредитование ипотеки"]

  - id: CURRENCY_EXCHANGE
    name: "Обмен валют"
    synonyms: ["обмен валют","курс валют","купить валюту","продать валюту"]

  - id: MONEY_TRANSFERS
    name: "Денежные переводы"
    synonyms: ["денежный перевод","перевести деньги","межбанковский перевод","swift","p2p перевод"]

  - id: MOBILE_APP
    name: "Мобильное приложение"
    synonyms: ["мобильное приложение","мобильный банк","приложение","телекард","сбой приложения"]

  - id: PKO
    name: "ПКO (приём кассовых операций)"
    synonyms: ["пко","приём наличных","кассовые операции"]

  - id: ACQUIRING
    name: "Эквайринг"
    synonyms: ["эквайринг","торговый эквайринг","интернет-эквайринг","терминал для оплаты"]

  - id: BRANCH_SERVICE
    name: "Обслуживание в отделении"
    synonyms: ["обслуживание","отделение","операционист","офис банка","очередь в отделении"]

  - id: REMOTE_SERVICE
    name: "Дистанционное обслуживание"
    synonyms: ["дистанционное обслуживание","онлайн-банк","личный кабинет","интернет-банк"]

  - id: OTHER_SERVICES
    name: "Другие услуги"
    synonyms: ["услуга","сервис","банковские продукты","дополнительные услуги"]

sentiment_labels: ["neg","neu","pos"]
